const state={stocks:[],dates:[],times:[],selectedSymbol:'RELIANCE',side:'BUY',replayTimer:null,replaying:false,points:[]};
const $=id=>document.getElementById(id);
const money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const pct=v=>(Number(v||0)>=0?'+':'')+Number(v||0).toFixed(2)+'%';
async function api(url,opts){const r=await fetch(url,opts);const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d}
function toast(msg,error=false){const el=$('toast');el.textContent=msg;el.className='toast show'+(error?' error':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',2800)}
function set(id,v){$(id).textContent=v}
function signedMoney(v){return (Number(v)>=0?'+':'−')+money(Math.abs(v))}
async function init(){
  const d=await api('/api/stocks');state.stocks=d.stocks;state.dates=d.dates;state.times=d.times;set('recordCount',d.record_count.toLocaleString('en-IN'));set('datasetRange',`${d.dates[0]} → ${d.dates[d.dates.length-1]}`);set('stockCount',`${d.stocks.length} stocks`);
  $('dateSelect').innerHTML=d.dates.map(x=>`<option value="${x}">${x}</option>`).join('');$('timeSelect').innerHTML=d.times.map(x=>`<option value="${x}">${x}</option>`).join('');$('dateSelect').value=d.dates[d.dates.length-1];$('timeSelect').value=d.times[d.times.length-1];
  renderStocks();bind();await refreshAll();
}
function bind(){
  $('stockSearch').addEventListener('input',renderStocks);$('dateSelect').addEventListener('change',refreshMarket);$('timeSelect').addEventListener('change',refreshMarket);$('quantity').addEventListener('input',updateEstimate);$('replayBtn').addEventListener('click',toggleReplay);$('placeOrder').addEventListener('click',placeOrder);$('resetBtn').addEventListener('click',resetDemo);$('focusTrade').addEventListener('click',()=>document.getElementById('tradeSection').scrollIntoView({behavior:'smooth'}));
  document.querySelectorAll('.side-tab').forEach(b=>b.addEventListener('click',()=>{state.side=b.dataset.side;document.querySelectorAll('.side-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');updateOrderMode();}));
  document.querySelectorAll('.qty-control button').forEach(b=>b.addEventListener('click',()=>{const input=$('quantity');input.value=Math.max(1,(parseInt(input.value||1)+Number(b.dataset.step)));updateEstimate()}));
}
function renderStocks(){const q=$('stockSearch').value.trim().toLowerCase();const list=state.stocks.filter(s=>(s.symbol+' '+s.company_name).toLowerCase().includes(q));$('stockList').innerHTML=list.map(s=>`<div class="watch-item ${s.symbol===state.selectedSymbol?'active':''}" data-symbol="${s.symbol}"><div><div class="watch-symbol">${s.symbol}</div><div class="watch-company">${s.company_name}</div></div><div><div class="watch-price">${money(s.latest_price)}</div><div class="watch-change ${s.change>=0?'up':'down'}">${s.change>=0?'+':''}${s.change.toFixed(2)} · ${s.change_pct>=0?'+':''}${s.change_pct.toFixed(2)}%</div></div></div>`).join('')||'<div class="empty">No instruments match your search.</div>';document.querySelectorAll('.watch-item').forEach(x=>x.onclick=()=>{state.selectedSymbol=x.dataset.symbol;renderStocks();refreshAll()})}
async function refreshAll(){await refreshMarket();await refreshPortfolio();await refreshTransactions()}
async function refreshMarket(){try{const symbol=state.selectedSymbol,date=$('dateSelect').value,time=$('timeSelect').value;const d=await api(`/api/market?symbol=${encodeURIComponent(symbol)}&date=${date}&time=${time}`);set('selectedStock',`${d.company_name} `);$('selectedStock').innerHTML=`${d.company_name} <small>${d.symbol}</small>`;set('selectedPrice',money(d.price));const c=$('priceChange');c.textContent=`${d.change>=0?'+':''}${money(d.change)} (${d.change_pct>=0?'+':''}${d.change_pct.toFixed(2)}%)`;c.className='change '+(d.change>0?'up':d.change<0?'down':'neutral');set('dayOpen',money(d.day_open));set('dayHigh',money(d.day_high));set('dayLow',money(d.day_low));set('sessionPoints',d.session_points);set('orderSymbol',d.symbol);set('orderPrice',money(d.price));updateOrderMode();const s=await api(`/api/series?symbol=${encodeURIComponent(symbol)}&date=${date}`);state.points=s.points;drawChart(s.points);set('axisStart',s.points[0]?.trading_time||'—');set('axisEnd',s.points[s.points.length-1]?.trading_time||'—');updateEstimate()}catch(e){toast(e.message,true)}}
function drawChart(points){const svg=$('priceChart');if(!points.length){svg.innerHTML='';return}const W=1000,H=360,pad={l:28,r:22,t:22,b:28};const vals=points.map(p=>Number(p.price));const min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;const x=i=>pad.l+i*(W-pad.l-pad.r)/Math.max(1,points.length-1);const y=v=>pad.t+(max-v)*(H-pad.t-pad.b)/range;const coords=points.map((p,i)=>[x(i),y(Number(p.price))]);const poly=coords.map(c=>c.join(',')).join(' ');const area=`${pad.l},${H-pad.b} ${poly} ${W-pad.r},${H-pad.b}`;let grid='';for(let i=0;i<5;i++){const yy=pad.t+i*(H-pad.t-pad.b)/4;grid+=`<line class="chart-grid" x1="${pad.l}" y1="${yy}" x2="${W-pad.r}" y2="${yy}"/>`}svg.innerHTML=`<defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#31d7d2" stop-opacity=".20"/><stop offset="1" stop-color="#31d7d2" stop-opacity="0"/></linearGradient></defs>${grid}<polygon class="chart-area" points="${area}"/><polyline class="chart-line" points="${poly}"/>${coords.length?`<circle class="chart-dot" cx="${coords[coords.length-1][0]}" cy="${coords[coords.length-1][1]}" r="5"/>`:''}`}
function updateOrderMode(){const price=$('orderPrice').textContent;set('placeOrder',(state.side==='BUY'?'Buy ':'Sell ')+state.selectedSymbol);$('placeOrder').classList.toggle('sell-mode',state.side==='SELL');updateEstimate()}
function updateEstimate(){const price=parseFloat(($('orderPrice').textContent||'0').replace(/[^0-9.]/g,''))||0;const qty=Math.max(0,parseInt($('quantity').value||0));set('estimatedValue',money(price*qty))}
async function refreshPortfolio(){const d=await api('/api/portfolio');set('heroCash',money(d.cash));set('heroEquity',money(d.total_value));set('heroPnl',signedMoney(d.total_pnl));set('totalValue',money(d.total_value));set('totalPnl',pct(d.return_pct));set('marketValue',money(d.market_value));set('exposurePct',`${d.total_value?((d.market_value/d.total_value)*100).toFixed(2):'0.00'}% of equity`);set('realizedPnl',signedMoney(d.realized_pnl));set('unrealizedPnl',signedMoney(d.unrealized_pnl));set('investedCost',money(d.invested_cost));set('portfolioCash',money(d.cash));set('portfolioReturn',pct(d.return_pct));set('positionCount',`${d.positions.length} position${d.positions.length===1?'':'s'}`);$('positions').innerHTML=d.positions.length?d.positions.map(p=>`<div class="position"><div><div class="position-title">${p.symbol} <span style="color:#627b94;font-weight:600">· ${p.quantity} shares</span></div><div class="position-meta">Avg ${money(p.avg_cost)} · Last ${money(p.current_price)}</div></div><div class="position-right"><div class="position-pnl ${p.unrealized_pnl>=0?'up':'down'}">${signedMoney(p.unrealized_pnl)} · ${pct(p.return_pct)}</div><div class="position-value">${money(p.market_value)}</div></div></div>`).join(''):'<div class="empty">No open positions yet.<br>Use the order ticket to place your first paper trade.</div>';const base=Math.max(1,INITIAL_EQUITY_PLACEHOLDER);$('equityProgress').style.width=Math.min(100,Math.max(4,d.total_value/base*100))+'%'}
const INITIAL_EQUITY_PLACEHOLDER=1000000;
async function refreshTransactions(){const d=await api('/api/transactions');$('transactions').innerHTML=d.transactions.length?d.transactions.map(t=>`<tr><td><span class="side-badge ${t.side.toLowerCase()}">${t.side}</span></td><td><strong>${t.symbol}</strong><div style="color:#5f7790;font-size:8px">${t.company_name||''}</div></td><td>${t.quantity}</td><td>${money(t.price)}</td><td>${t.trading_date} · ${t.trading_time}</td><td>${money(t.value)}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">No transactions yet. Your first paper trade will appear here.</td></tr>'}
async function placeOrder(){const btn=$('placeOrder');const qty=parseInt($('quantity').value||0);if(!Number.isInteger(qty)||qty<=0){toast('Enter a positive whole-share quantity.',true);return}btn.disabled=true;try{const d=await api('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol:state.selectedSymbol,side:state.side,date:$('dateSelect').value,time:$('timeSelect').value,quantity:qty})});$('orderMessage').textContent=d.message;$('orderMessage').style.color='#56e1a0';toast(d.message);await refreshPortfolio();await refreshTransactions()}catch(e){$('orderMessage').textContent=e.message;$('orderMessage').style.color='#ff8b96';toast(e.message,true)}finally{btn.disabled=false}}
async function resetDemo(){if(!confirm('Reset the demo account, holdings and transaction history?'))return;await api('/api/reset',{method:'POST'});$('orderMessage').textContent='Demo account reset successfully.';$('orderMessage').style.color='#56e1a0';toast('Demo account reset');await refreshAll()}
function toggleReplay(){if(state.replaying){clearInterval(state.replayTimer);state.replaying=false;$('replayBtn').innerHTML='▶ <span>Replay</span>';return}state.replaying=true;$('replayBtn').innerHTML='⏸ <span>Pause</span>';state.replayTimer=setInterval(()=>{let i=state.times.indexOf($('timeSelect').value);i=(i+1)%state.times.length;$('timeSelect').value=state.times[i];refreshMarket()},1000)}
window.addEventListener('beforeunload',()=>clearInterval(state.replayTimer));init().catch(e=>{document.body.innerHTML=`<div style="padding:40px;color:white;font-family:system-ui">Unable to start TradeSim Pro: ${e.message}</div>`});
